Repository MovingBlocks/movingblocks.github.com, pull requests merged in 2022-12, with the labels that each got.

#122 build(deps): run 'yarn upgrade'
  yarn.lock
Labels: dependencies

#123 chore: remove 'deploy-github' script and improve setup docs
  README.md
  package.json
  scripts/deploy-github.js
  yarn.lock
Labels: dependencies

#126 fix(search): make search lookups more resilient and collect required information in search index
  gatsby-node.js
  package.json
  src/templates/blog.jsx
  src/templates/modulelist.jsx
Labels: bug

#128 build(deps): update to Gatsby v4
  package.json
  src/components/Home/Index.jsx
  src/templates/blog.jsx
  src/templates/modulelist.jsx
  yarn.lock
Labels: enhancement, dependencies

#130 fix: mentor page customField references
  src/components/Mentor/Mentor.jsx
  src/components/MentorModal/MentorModal.jsx
Labels: bug

#131 fix: replace gatsby-plugin-react-helmet with Gatsby Head API
  data/SiteConfig.js
  gatsby-config.js
  package.json
  src/components/Mentor/Mentor.jsx
  src/components/SEO/SEO.jsx
  src/hooks/use-site-metadata.jsx
  src/layout/index.jsx
  src/pages/404.jsx
  src/pages/downloads.jsx
  src/pages/game.jsx
  src/pages/gsoc_tsoc.jsx
  src/pages/index.jsx
  src/pages/media.jsx
  src/pages/mentors.jsx
  src/templates/blog.jsx
  src/templates/modulelist.jsx
  src/templates/modules.jsx
  src/templates/post.jsx
  yarn.lock
Labels: bug

#139 ci: upgrade node version to >= 18.0.0
  .github/workflows/build.yml
  .github/workflows/lint.yml
  package.json
Labels: dependencies

#144 fix: image collection for "Media" page
  src/components/Media/Media.jsx
Labels: bug

#145 build(deps): remove unused dependencies
  data/SiteConfig.js
  gatsby-config.js
  package.json
  yarn.lock
Labels: dependencies

#140 ci: upgrade eslint version to >= 8.30.0
  .eslintrc.json
  gatsby-node.js
  package.json
  src/components/About/About.jsx
  src/components/BlogSearchForm/BlogSearchForm.jsx
  src/components/Cards/Cards.jsx
  src/components/Download/Download.jsx
  src/components/Footer/Footer.jsx
  src/components/GsocTsoc/GsocTsoc.jsx
  src/components/Header/Header.jsx
  src/components/Home/Index.jsx
  src/components/Media/Media.jsx
  src/components/MediaPagination/MediaPagination.jsx
  src/components/Mentor/Mentor.jsx
  src/components/MentorModal/MentorModal.jsx
  src/components/PostListing/PostListing.jsx
  src/components/PostTags/PostTags.jsx
  src/components/ProjectModal/ProjectModal.jsx
  src/components/SEO/SEO.jsx
  src/components/SearchForm/SearchForm.jsx
  src/components/SearchResult/SearchResult.jsx
  src/components/SocialLinks/SocialLinks.jsx
  src/layout/index.jsx
  src/pages/404.jsx
  src/pages/downloads.jsx
  src/pages/game.jsx
  src/pages/gsoc_tsoc.jsx
  src/pages/index.jsx
  src/pages/media.jsx
  src/pages/mentors.jsx
  src/templates/blog.jsx
  src/templates/modulelist.jsx
  src/templates/modules.jsx
  src/templates/post.jsx
  yarn.lock
Labels: dependencies

#151 fix: blog search navigation when using pathPrefix
  src/components/BlogSearchForm/BlogSearchForm.jsx
  src/components/SearchForm/SearchForm.jsx
  src/templates/blog.jsx
  src/templates/modulelist.jsx
Labels: bug

#154 feat: remove explicit display date 'ddate'
  blog/2017-06-14-say-hello-to-our-new-website/index.md
  blog/2017-07-14-gsoc-2017-an-overview/index.md
  blog/2017-09-17-lost-exploration-world/index.md
  blog/2017-11-28-google-code-in-with-tiled/index.md
  blog/2018-09-02-gsoc-2018-results/index.md
  blog/2018-09-29-happy-7th-birthday-terasology/index.md
  blog/2019-05-29-gsoc-2019-an-overview/index.md
  blog/2019-09-27-looking-back-at-gsoc-2019/index.md
  blog/2019-10-28-teracon-munich-and-mentor-summit/index.md
  blog/2020-01-25-terasaturday-1/index.md
  blog/2020-02-01-terasaturday-2/index.md
  blog/2020-05-30-gsoc-2020-an-overview/index.md
  blog/2020-05-30-terasaturday-3-core-explosion/index.md
  blog/2020-06-06-terasaturday-4-the-gradle-will-rock/index.md
  blog/2020-07-19-gsoc-2020-halftime/index.md
  blog/2020-09-27-gsoc-2020-conclusion/index.md
  blog/2020-11-21-terasaturday-5-do-all-the-changes/index.md
  blog/2020-11-28-terasaturday-6-hide-and-sheep/index.md
  blog/2020-12-05-terasaturday-7-its-a-new-spawn-its-a-new-day/index.md
  blog/2020-12-25-terasaturday-8-a-merry-gooey-christmas/index.md
  blog/2021-01-30-terasaturday-9-happy-new-year/index.md
  blog/2021-02-07-teraspotlight-extreme-view-distances-with-lod-chunks/index.md
  blog/2021-02-27-terasaturday-10-consider-us-joml-ified/index.md
  blog/2021-03-13-terasaturday-11-gsoc-2021-is-coming/index.md
  blog/2021-03-20-terasaturday-12-whatever-floats-your-island/index.md
  blog/2021-04-17-terasaturday-13-may-the-maven-be-with-us/index.md
  blog/2021-05-02-teraspotlight-contributor-pulse-check/index.md
  blog/2021-05-16-terasaturday-14-spring-cleanup/index.md
  blog/2021-06-01-teraspotlight-gsoc-2021-projects/index.md
  blog/2021-07-24-teraspotlight-gsoc-2021-halftime-show-tell/index.md
  blog/2021-07-31-terasaturday-15-a-summer-of-code/index.md
  data/SiteConfig.js
  docs/blog-documentation.md
  gatsby-node.js
  src/components/Cards/Cards.jsx
  src/components/PostListing/PostListing.jsx
  src/components/SearchResult/SearchResult.jsx
  src/templates/blog.jsx
  src/templates/post.jsx
Labels: enhancement

#162 fix(modules): add missing cover image information to search index
  gatsby-node.js
Labels: bug

#163 feat: overhaul cards
  src/components/Cards/Cards.jsx
  src/components/PostListing/PostListing.jsx
  src/components/SearchResult/SearchResult.jsx
  src/layout/css/_cards.scss
  src/layout/css/_typography.scss
  src/templates/BlogList.jsx
  src/templates/ModuleList.jsx
Labels: enhancement

#165 fix: img aspect ratio for search result cards
  gatsby-node.js
Labels: bug

#170 fix: remove "Explore" link and fix missing path prefixes
  package.json
  src/components/About/About.jsx
  src/components/Header/Header.jsx
Labels: bug
